version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NODE_ENV=${NODE_ENV}
    environment:
      - NODE_ENV=${NODE_ENV}
      - DB_CONNECT=${DB_CONNECT}
      - PORT=${PORT}
    ports:
      - 8000:3000
    depends_on:
      - elasticsearch
      - logstash

  nexus:
    image: sonatype/nexus3:3.33.0
    ports:
      - "8081:8081"
      - "8123:8123"
    volumes:
      - ./nexus-data:/nexus-data

  postgres:
    image: postgres:13.3
    ports:
      - 5432:5432
    depends_on:
      - elasticsearch
      - logstash
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=db
    logging:
      driver: gelf
      options:
        gelf-address: "udp://172.17.0.1:12201"
        tag: "postgres"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.14.0
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - cluster.routing.allocation.disk.threshold_enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200

  kibana:
    image: docker.elastic.co/kibana/kibana:7.14.0
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch
      - logstash
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
      ELASTICSEARCH_HOSTS: '["http://elasticsearch:9200"]'
      networks:

  logstash:
    image: docker.elastic.co/logstash/logstash:7.14.0
    links:
      - elasticsearch
    volumes:
      - ./config/logstash.conf:/etc/logstash/logstash.conf
    command: logstash -f /etc/logstash/logstash.conf
    ports:
      - 12201:12201/udp
    depends_on:
      - elasticsearch